### ISSUE TITLE
Block formulas

### ISSUE THREAD

**Issue by jtrussell** [GitbookIO/plugin-katex#1]
Thanks for the plugin, I was trying to switch from the mathjax plugin to this one and couldn't seem to get block formulas to render in the same way.

With mathjax if I put a formula on line by itself, e.g.:

```
Some text

$$ formula $$

More text
```

The formula will be rendered on a line by itself and centered. With this plugin I don't seem to get the centering and there's no bottom margin. Is this intentional or just due to this being in alpha?

**Comment by SamyPesse** [comment]
What version of GitBook are you using?

**Comment by jtrussell** [comment]
Version 1.5.0.

**Comment by jtrussell** [comment]
I'm on a different machine and can't seem to reproduce my issue this morning though. I'll close this now and reopen if I'm able to reproduce. Sorry for the confusion!

**Comment by emilbayes** [comment]
I can't seem to get block formulas to work either. The following formular renders the inline version of the integral sign:

``` markdown
Introduction and Maps I
=======================

$$\int_{-\infty}^\infty g(x) dx$$

Systems
-------

###Maps
```

I'm using Gitbook CLI `0.3.6` and Gitbook `2.3.0`

**Comment by SamyPesse** [comment]
I just published version `1.1.0` that fixes it and respect the same convention as MathJax:

```
Inline math: $$\int_{-\infty}^\infty g(x) dx$$


Block math:

$$
\int_{-\infty}^\infty g(x) dx
$$
```

is rendered as:

![screen shot 2015-09-07 at 14 37 33](https://cloud.githubusercontent.com/assets/845425/9716890/715d6aa8-556e-11e5-854b-8fee10b557ca.png)

**Comment by emilbayes** [comment]
@SamyPesse Do you know why the integral sign in the block math is still rendered as an inline integral?
An issue in KaTeX? This is what it should look like:

![Block Integral Sign](https://www.sharelatex.com/learn-scripts/images/a/a5/Integral2.png)

([Source](https://www.sharelatex.com/learn/Integrals,_sums_and_limits#Integrals))

**Comment by SamyPesse** [comment]
@emilbayes  I just fixed it: https://github.com/GitbookIO/plugin-katex/commit/1ca925b8586c3c0ace513c5fddc1363cf7d5eb4b

Release is coming soon
