### ISSUE TITLE
Can not display number sets 

### ISSUE THREAD

**Issue by yageek** [GitbookIO/plugin-katex#3]
I would like to display number of set using the `\mathbb` statement but it does not work:

```
KaTeX parse error: Expected 'EOF', got '\mathbb' at position 7: \mathbb̲{R}
```

The Gitbook editors renders it well but I can not build the ebook.

**Comment by SamyPesse** [comment]
[Katex](https://github.com/Khan/KaTeX) doesn`t support everything that MathJax does, you should switch to MathJax (https://github.com/GitbookIO/plugin-mathjax)
