### ISSUE TITLE
Does not work with GLOSSARY.md

### ISSUE THREAD

**Issue by emilbayes** [GitbookIO/plugin-katex#5]
Doesn't seem to render formulas in Glossary items. Not sure if this is a bug here, or in GitbookIO/gitbook.

Example:

`README.md`:  

``` markdown
Difference equation
```

`GLOSSARY.md`:  

``` markdown
# Difference equation
$$x_{n+1} = f(x_n)$$
```

**Comment by SamyPesse** [comment]
There is already an issue on gitbook for this: https://github.com/GitbookIO/gitbook/issues/873
