### ISSUE TITLE
`gitbook serve` crashes on error

### ISSUE THREAD

**Issue by emilbayes** [GitbookIO/plugin-katex#6]
Looking at [`Khan/KaTeX`](https://github.com/Khan/KaTeX#rendering-options), there's an option `throwOnError` that could be set to false here. Otherwise the body of the [`process`](https://github.com/GitbookIO/plugin-katex/blob/70f743bf7a9aa99751bf99169749d5eca48971de/index.js#L24) function should probably be wrapped in a `try { … } catch (ex) { … }`, if it's possible to tell Gitbook that an error occured

**Comment by SamyPesse** [comment]
This is wanted, when there is an error, we want gitbook to stop and output the error to the user.
